name: ncc
on:
  push:
    # Can't push a build commit to a tag, so only run for branches
    branches:
      - '**'
    paths:
      # Include any files that could require rebuilding
      - 'package-lock.json'
      - 'src/**'

jobs:
  ncc-build:
    uses: planningcenter/balto-utils/.github/workflows/ncc.yml@v1
